# Generated by Django 3.0.7 on 2020-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
