# Generated by Django 3.0.7 on 2020-06-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_answer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
    ]
