# Generated by Django 3.0.7 on 2020-06-19 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200618_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
