# Generated by Django 3.0.7 on 2020-06-21 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_question_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
